### ISSUE TITLE
please optional kar do mongodb ko jaise suhail md ne ki hui hai

### ISSUE THREAD

**Issue by officialgmshah** [naveeddogar/KING-MD#59]
mongo db ko optional kar do yaar please woh na deni pade pata nahi kion mujh se mongodb nahi banti video dekh kr bnata bhi hu par woh work hi nahi krti

**Comment by naveeddogar** [comment]
> mongo db ko optional kar do yaar please woh na deni pade pata nahi kion mujh se mongodb nahi banti video dekh kr bnata bhi hu par woh work hi nahi krti

##REPLY

Ok ager Apko mongodb chhaiyay to telegram aao
